# Psyradox
def test_import():
    import justorservice.styles
    import justorservice.database
    import justorservice.gamedig
    import justorservice.logger
    import justorservice.main
    import justorservice.server
    import justorservice.service
